### ISSUE TITLE
Videos don't play

### ISSUE THREAD

**Issue by savahu** [bingnz/Pluralsight.bundle#1]
Hi, are you still developing this?
The channel allows me to select a course, but then the video does not play, with the error message 'Channel does not respond'.

**Comment by bingnz** [comment]
Hi,

I think I've made one or two changes since you posted this issue. Sorry it's taken me so long to see this message, I didn't actually look at the GitHub page! Do you still have problems playing videos? Does it work in the browser on your Plex server?
If you're still having problems, try upgrading your Plex server to the latest version. If that doesn't help, please attach the log file (you can find the plugin logs for your platform using these [instructions](https://support.plex.tv/hc/en-us/articles/201106148-Channel-Log-Files)) and I can try to figure out what's going wrong.

Thanks,
David
